### PR TITLE
Readme image embed from gdrive

### PR DESCRIPTION
**Pull request by MikeJeffers**
Is there an effective way to test this without pushing to github?

### CODE REVIEW

**Comment by brimoor** [comment]
that's a big image:
Screen Shot 2020-01-22 at 5 41 00 PM

**Comment by brimoor** [comment]
@MikeJeffers here's how to test such things locally before pushing: https://github.com/joeyespo/grip

**Comment by lethosor** [comment]
You can also edit + preview markdown files in the GitHub web editor: https://github.com/voxel51/platform-integrations/edit/develop/README.md

**Comment by lethosor** [comment]
This is giving me the same issue FYI:
image
might want to host it somewhere else

**Comment by lethosor** [comment]
Trying this:

image

image

**Comment by lethosor** [comment]
@MikeJeffers that seems to work. Could update occurrences of these image(s) in other repos to use these links, since they're showing the same issue currently.

**Comment by MikeJeffers** [comment]
I approve your changes.
And I agree, I used the gdrive strategy because it was used elsewhere, and might be easier for others to control and manipulate the content outside of github.  This is better, rather have to update the image on github, than not have it show half the time

**Review by lethosor — APPROVED** [review]
Per above

**Pull request merged**
